# Generated by Django 4.2.6 on 2023-10-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('cat_description', models.TextField(max_length=500, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('cat_name',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('prod_description', models.TextField(max_length=500, verbose_name='описание')),
                ('prod_preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='превью')),
                ('prod_category', models.CharField(max_length=100, verbose_name='категория')),
                ('prod_price', models.IntegerField(verbose_name='цена за покупку')),
                ('prod_date_of_create', models.DateTimeField(verbose_name='дата создания')),
                ('prod_date_of_last_change', models.DateTimeField(verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('prod_name',),
            },
        ),
    ]
