# Generated by Django 4.2.6 on 2023-11-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('note_body', models.TextField(verbose_name='содержимое')),
                ('note_preview', models.ImageField(blank=True, null=True, upload_to='notes/', verbose_name='превью')),
                ('note_date_of_create', models.DateTimeField(verbose_name='дата создания')),
                ('note_views_count', models.IntegerField(default=0, verbose_name='просмотры')),
                ('note_is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'блоговая запись',
                'verbose_name_plural': 'блоговые записи',
            },
        ),
    ]
