# Generated by Django 4.2.6 on 2023-11-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('note_title',), 'verbose_name': 'блоговая запись', 'verbose_name_plural': 'блоговые записи'},
        ),
        migrations.AlterField(
            model_name='note',
            name='note_date_of_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
