# Generated by Django 4.2.6 on 2023-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_products_prod_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_date_of_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
