# Generated by Django 4.2.6 on 2023-12-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_products_prod_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_is_published',
            field=models.BooleanField(default=True),
        ),
    ]
