# Generated by Django 4.2.6 on 2023-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_products_prod_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_is_published',
            field=models.BooleanField(default=True, verbose_name='запись опубликована'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_is_published',
            field=models.BooleanField(default=True, verbose_name='продукт опубликован'),
        ),
    ]
